name: Build Kivy APK

on:
  push:
    branches:
      - main  # Trigger this on the main branch (or your specific branch)

jobs:
  build:
    runs-on: ubuntu-24.04  # Use the latest Ubuntu version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Android SDK and NDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          # Set up Android SDK and NDK
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $ANDROID_SDK_ROOT
          rm commandlinetools.zip
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;21.3.6528147"

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython python-for-android

      - name: Verify installed dependencies
        run: |
          source venv/bin/activate
          pip freeze

      - name: Clean previous builds
        run: |
          source venv/bin/activate
          buildozer android clean || echo "Clean failed, continue anyway"

      - name: Build APK using Buildozer
        run: |
          source venv/bin/activate
          set -x
          export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.2:$ANDROID_SDK_ROOT/build-tools/30.0.3:$PATH"
          ./venv/bin/buildozer android debug --debug --log_level=2 || { echo "Buildozer failed"; exit 1; }
          set +x

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: ./bin/app-debug.apk
