name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger build on pull request to main

jobs:
  build:
    runs-on: ubuntu-latest  # Run the build on the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev openjdk-8-jdk zlib1g-dev
        python -m pip install --upgrade pip
        python -m pip install buildozer

    - name: Install Android SDK
      run: |
        sudo apt-get install -y android-sdk
        echo "sdk.dir=/usr/lib/android-sdk" > local.properties

    - name: Build APK using Buildozer
      run: |
        buildozer android debug  # This command will build the APK in debug mode

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: eye_disease_detector-debug.apk
        path: ./bin/*.apk  # Ensure this points to the location of the APK
