name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # You can change this to the branch you use to trigger builds
  pull_request:
    branches:
      - main  # You can change this to the branch you use to trigger builds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can adjust to a specific Python version if necessary

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          python3-pip \
          git \
          unzip \
          openjdk-8-jdk \
          zlib1g-dev
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt  # Ensure you have your requirements listed

    - name: Install Buildozer
      run: |
        python -m pip install buildozer

    - name: Set up Android SDK
      run: |
        sudo apt-get install -y android-sdk
        echo "sdk.dir=/usr/lib/android-sdk" > local.properties

    - name: Set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
        unzip android-ndk-r21d-linux-x86_64.zip
        sudo mv android-ndk-r21d /usr/local/android-ndk
        echo "ndk.dir=/usr/local/android-ndk" >> local.properties

    - name: Build APK using Buildozer
      run: |
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: eye_disease_detector-debug.apk
        path: ./bin/*.apk  # This path should correctly point to the APK location
