name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK + Build Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d temp
          mv temp/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;33.0.2" \
            "build-tools;30.0.3"  # Trying another build-tools version for AIDL compatibility

      - name: List Android SDK directories (Debugging Step)
        run: |
          echo "Listing platform-tools:"
          ls -l $ANDROID_SDK_ROOT/platform-tools
          echo "Listing cmdline-tools:"
          ls -l $ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          echo "Listing build-tools:"
          ls -l $ANDROID_SDK_ROOT/build-tools/33.0.2
          ls -l $ANDROID_SDK_ROOT/build-tools/30.0.3  # Check another version of build-tools

      - name: Add Android SDK Tools to PATH (including AIDL)
        run: |
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/33.0.2" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/30.0.3" >> $GITHUB_PATH

          # Check if AIDL exists and is executable in both versions
          if [ -f "$ANDROID_SDK_ROOT/build-tools/33.0.2/aidl" ]; then
            echo "✅ AIDL found in 33.0.2"
            chmod +x $ANDROID_SDK_ROOT/build-tools/33.0.2/aidl
            ls -l $ANDROID_SDK_ROOT/build-tools/33.0.2/aidl  # Ensure it's executable
            which aidl
            aidl --version || echo "✅ AIDL is now executable in 33.0.2"
          elif [ -f "$ANDROID_SDK_ROOT/build-tools/30.0.3/aidl" ]; then
            echo "✅ AIDL found in 30.0.3"
            chmod +x $ANDROID_SDK_ROOT/build-tools/30.0.3/aidl
            ls -l $ANDROID_SDK_ROOT/build-tools/30.0.3/aidl  # Ensure it's executable
            which aidl
            aidl --version || echo "✅ AIDL is now executable in 30.0.3"
          else
            echo "❌ AIDL not found in either build-tools version!"
            exit 1
          fi

      - name: Run AIDL Debugging Command (Full Path)
        run: |
          echo "Running AIDL with full path..."
          if [ -f "$ANDROID_SDK_ROOT/build-tools/33.0.2/aidl" ]; then
            $ANDROID_SDK_ROOT/build-tools/33.0.2/aidl --help
          fi

      - name: Build APK using Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseDetector-APK
          path: bin/*.apk
