name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip git zip libffi-dev libssl-dev \
                              libsqlite3-dev libbz2-dev libtinfo6 build-essential python3-pip

          # Installing Android SDK command-line tools
          sudo apt install -y openjdk-11-jdk
          sudo apt install -y android-sdk

          # Setting up Android SDK environment variables
          echo "export ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize buildozer.spec if missing
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Install Android SDK Components (including AIDL)
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "tools" "tools\bin"
          yes | sdkmanager "ndk;21.4.7075529" "cmake;3.10.2.4988404" "patcher;v4" "extras;google;m2repository" "extras;android;m2repository" "extras;google;google_play_services"

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseApp-APK
          path: ./bin/*.apk
