name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev zip unzip openjdk-11-jdk
          python -m pip install --upgrade pip
          pip install cython buildozer python-for-android

      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          android-api-level: '31'
          ndk-version: '25.2.9519653'

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/Android/Sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64" >> $GITHUB_ENV

      - name: Build APK with Buildozer
        run: buildozer -v android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: ./bin/*.apk

      - name: Upload Build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            .buildozer/android/platform/build-*/dists/*/build/intermediates/*/logs/**/*.txt
            .buildozer/android/platform/build-*/build/*.log
            .buildozer/*.log
