name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java 11
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install Android SDK, NDK, and Build Tools
      - name: Install Android SDK, NDK, and Build Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d temp
          mv temp/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-31" "build-tools;33.0.2" "build-tools;30.0.3" "ndk;21.3.6528147"

      # List SDK directories (for debugging)
      - name: List SDK directories (Debug)
        run: |
          ls -l $ANDROID_SDK_ROOT/platform-tools
          ls -l $ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          ls -l $ANDROID_SDK_ROOT/build-tools/33.0.2

      # Add SDK tools to PATH
      - name: Add SDK tools to PATH
        run: |
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/33.0.2" >> $GITHUB_PATH

      # Install Buildozer, python-for-android, and dependencies
      - name: Install Buildozer, python-for-android, and dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython python-for-android
          pip list  # Show installed packages to debug

      # Clean previous builds
      - name: Clean previous builds
        run: |
          source venv/bin/activate
          buildozer android clean || echo "Clean failed, continue anyway"

      # Build APK using Buildozer
      - name: Build APK using Buildozer
        run: |
          source venv/bin/activate
          set -x
          export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.2:$ANDROID_SDK_ROOT/build-tools/30.0.3:$PATH"
          ./venv/bin/buildozer android debug --debug || { echo "Buildozer failed"; exit 1; }
          set +x

      # Upload APK as an artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseDetector-APK
          path: bin/*.apk
