name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # <-- Use stable LTS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK using Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseDetector-APK
          path: bin/*.apk
