on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Check the Ubuntu version
      - name: Check Ubuntu version
        run: |
          uname -a
          lsb_release -a

      # Install libtinfo6 to resolve the issue
      - name: Install libtinfo6
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo6

      # Install libncurses6 to resolve the issue
      - name: Install libncurses6
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses6

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
