name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install system & Python dependencies
      - name: Install system dependencies and Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev zip unzip
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      # Step 4: Build APK with verbose logs
      - name: Build APK with Buildozer
        run: buildozer --log-level debug -v android debug

      # Step 5: Upload the generated APK
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: ./bin/*.apk

      # Step 6: Upload build logs on failure
      - name: Upload Buildozer Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            .buildozer/android/platform/build-*/dists/*/build/intermediates/*/logs/**/*.txt
            .buildozer/android/platform/build-*/build/*.log
            .buildozer/*.log
