name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libtinfo6 \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-8-jdk \  # Use OpenJDK 8 instead of 17
            python3-pip \
            python3-venv \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libbz2-dev \
            libreadline-dev \
            liblzma-dev \
            curl

      - name: Install Android NDK 25b
        run: |
          mkdir -p $HOME/android-ndk
          cd $HOME/android-ndk
          curl -LO https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          echo "ANDROIDNDK=$HOME/android-ndk/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/android-ndk/android-ndk-r25b" >> $GITHUB_ENV

      - name: Install Android SDK components
        run: |
          sudo apt-get install -y android-sdk
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-31"  # Install necessary SDK components

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build the APK
        run: |
          # Run Buildozer with increased verbosity for debugging
          buildozer -v -d android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseDetection-APK
          path: ./bin/*.apk
