name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-sdk/ndk/25.2.9519653
      ANDROID_NDK: ${{ github.workspace }}/android-sdk/ndk/25.2.9519653

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      - name: Install Android SDK and NDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d temp
          mv temp/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

      - name: Set SDK tools in PATH
        run: |
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/33.0.2" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel setuptools
          pip install buildozer==1.5.0 python-for-android==2023.10.06 cython==0.29.36

      - name: Convert model to TensorFlow Lite
        run: |
          source venv/bin/activate
          pip install tensorflow==2.14.0
          python3 -c "
          import tensorflow as tf
          model = tf.keras.models.load_model('eye_disease_model.h5')
          converter = tf.lite.TFLiteConverter.from_keras_model(model)
          tflite_model = converter.convert()
          open('eye_disease_model.tflite', 'wb').write(tflite_model)
          "

      - name: Initialize Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          # Update buildozer.spec with our settings
          sed -i '/^\[app\]/,/^\[/!d' buildozer.spec
          cat >> buildozer.spec <<EOL
[app]
title = Eye Disease Detector
package.name = eyediseasedetector
package.domain = org.eyedetector
source.dir = .
source.include_exts = py,png,jpg,kv,tflite
main.py = eyedisease.py
requirements = python3==3.9.13,kivy==2.2.1,plyer==2.1.0,Pillow==10.1.0,numpy==1.26.4,tflite-runtime==2.14.0
android.archs = arm64-v8a
android.api = 31
android.minapi = 21
android.ndk_path = $ANDROID_SDK_ROOT/ndk/25.2.9519653
android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE
orientation = portrait
log_level = 2
EOL

      - name: Build APK
        run: |
          source venv/bin/activate
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseDetector-APK
          path: bin/*.apk
