on:
  push:
    branches: [ main ]  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Running on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4  # Checkout the latest code

      # Step 2: Build the APK using Buildozer
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2  # Using the Buildozer action to build APK
        with:
          buildozer-cmd: buildozer -v android debug  # Command to build the APK

      # Step 3: Upload APK as artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v2  # Use the correct stable version v2 for uploading artifacts
        with:
          name: package
          path: ./bin/*.apk  # Ensure this path is where the APK is saved
