on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install system dependencies (including Cython)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          pip install --upgrade pip
          pip install cython  # Install Cython here
          pip install buildozer  # Install Buildozer

      # Step 4: Install the correct NDK version (version 25 or above)
      - name: Install Android NDK 25
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -P /tmp
          unzip /tmp/android-ndk-r25b-linux.zip -d $HOME/.buildozer/android/platform/
          mv $HOME/.buildozer/android/platform/android-ndk-r25b $HOME/.buildozer/android/platform/android-ndk

      # Step 5: Build APK using Buildozer
      - name: Build APK
        run: |
          buildozer -v android debug

      # Step 6: Upload the generated APK
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: ./bin/*.apk
