on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install Buildozer and dependencies
      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          pip install --upgrade pip
          pip install buildozer

      # Step 4: Build APK using Buildozer
      - name: Build APK
        run: |
          buildozer -v android debug

      # Step 5: Upload the generated APK
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: ./bin/*.apk
