name: Build Eye Disease APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manually install libtinfo5
        run: |
          sudo apt update
          wget http://archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libtinfo5_6.1-1ubuntu1.18.04_amd64.deb
          sudo dpkg -i libtinfo5_6.1-1ubuntu1.18.04_amd64.deb

      - name: Cache buildozer .buildozer & gradle
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
            ~/.gradle
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.9
          buildozer-cmd: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseDetector
          path: ./bin/*.apk
