name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip git zip libffi-dev libssl-dev \
                              libsqlite3-dev libbz2-dev libtinfo6 build-essential python3-pip

          # If libtinfo6 is not enough, manually install libtinfo5 if required.
          # Also, libncurses5 is often replaced by libncurses6 in modern systems.
          sudo apt install -y libtinfo5 || true
          sudo apt install -y libncurses6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize buildozer.spec if missing
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseApp-APK
          path: ./bin/*.apk
