name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - uses: actions/checkout@v4

      # Step 2: Use the Buildozer GitHub Action to build APK
      - name: Build APK using Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      # Step 3: Upload the generated APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EyeDiseaseApp-APK
          path: ./bin/*.apk
