name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.x
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install required dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev python3-pip python3-setuptools
          sudo apt-get install -y libgl1-mesa-glx libgles2-mesa
          sudo apt-get install -y zlib1g-dev liblzma-dev
          sudo apt-get install -y libfreetype6-dev libx11-dev libssl-dev
          sudo apt-get install -y libffi-dev
          sudo apt-get install -y libbz2-dev
          sudo apt-get install -y libncurses5-dev
          sudo apt-get install -y libsqlite3-dev
          sudo apt-get install -y libjpeg-dev liblcms2-dev libopenjp2-7
          sudo apt-get install -y libhdf5-dev
          sudo apt-get install -y unzip

      # Step 4: Install Python dependencies (Buildozer and other packages)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install kivy
          pip install tensorflow
          pip install tflite
          pip install pillow
          pip install plyer

      # Step 5: Install Android dependencies (Android SDK, NDK, etc.)
      - name: Install Android dependencies
        run: |
          sudo apt-get install -y openjdk-8-jdk
          sudo apt-get install -y libncurses5
          sudo apt-get install -y libstdc++6
          sudo apt-get install -y lib32z1
          sudo apt-get install -y lib32ncurses5
          sudo apt-get install -y lib32bz2-1.0
          sudo apt-get install -y lib32stdc++6
          sudo apt-get install -y lib32gcc1
          sudo apt-get install -y gcc-multilib
          sudo apt-get install -y g++-multilib

      # Step 6: Set up Android SDK and NDK
      - name: Set up Android SDK and NDK
        run: |
          mkdir -p $HOME/android-sdk-linux
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk-linux
          yes | $HOME/android-sdk-linux/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk-linux --licenses
          $HOME/android-sdk-linux/tools/bin/sdkmanager --update

      # Step 7: Install necessary Android SDK packages
      - name: Install Android SDK packages
        run: |
          $HOME/android-sdk-linux/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk-linux "platform-tools" "build-tools;31.0.0" "android-31" "ndk;23.1.7779620"

      # Step 8: Configure Buildozer
      - name: Configure Buildozer
        run: |
          # Create buildozer.spec file if it doesn't exist (optional)
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # Step 9: Build the APK using Buildozer
      - name: Build APK
        run: |
          buildozer android debug

      # Step 10: Upload APK as an artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: bin/*.apk
